Allow custom headers to be set in Server
StellarCN/py-stellar-base pull request #599
Opened 2022-06-10 21:26 UTC by RohitK89

This change allows users to pass in custom headers when instantiating a Server object, without needing to create an entire client by themselves.

This feature allows users to leverage the well-formed default client that has retry and backoff logic baked in already in situations where they need to pass in extra headers for their own tracking, or more critically, for authenticating against their Horizon provider.

# Testing

I tested this change locally and validated that tests are passing.

```
================================================================================================================= 972 passed, 62 skipped, 82 warnings in 6.23s =================================================================================================================
```

2022-06-11 21:47 UTC, RohitK89 commented
CC @overcat

2022-06-12 00:59 UTC, overcat requested changes

2022-06-12 00:59 UTC, overcat commented on stellar_sdk/client/requests_client.py
> +        custom_headers: Dict[str, str] = {},
I personally tend to modify it as follows, although this probably won't cause a bug in the current situation, for more information: https://stackoverflow.com/a/26320938

```suggestion
        custom_headers: Dict[str, str] = None,
```

2022-06-12 00:59 UTC, overcat commented on stellar_sdk/server.py
> +    :param custom_request_headers: Any headers that should be added when making HTTP requests to the
Personally, I prefer not to modify this file. Modifying headers is not a common requirement, and not every client implements the function of modifying headers. If a user has such a need, then he should create a client instance himself, it's not difficult in my opinion.

2022-06-12 11:29 UTC, closed without merging

2022-06-12 11:41 UTC, overcat commented
@RohitK89 Sorry, I closed this PR by mistake, can you re-push the code and reopen this PR? 🤦